<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS2BQWaU\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS2BQWaU/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS2BQWaU.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS2BQWaU\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerS2BQWaU\App_KernelDevDebugContainer([
    'container.build_hash' => 'S2BQWaU',
    'container.build_id' => '6eea601a',
    'container.build_time' => 1753350010,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS2BQWaU');
