<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBM6tBLt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBM6tBLt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBM6tBLt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBM6tBLt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBM6tBLt\App_KernelDevDebugContainer([
    'container.build_hash' => 'BM6tBLt',
    'container.build_id' => '730e4161',
    'container.build_time' => 1753283370,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBM6tBLt');
